package codegen

import (
	"fmt"
	"simplelang/ast"
	"strings"
)

func GenerateGoCode(stats []ast.Statement) string {
	var b strings.Builder

	printHeader(&b)
	printImports(&b, stats)

	b.WriteString("func main() {\n")
	for _, stat := range stats {
		b.WriteString("    ")
		b.WriteString(generateStatement(stat))
		b.WriteString("\n")
	}
	b.WriteString("}\n")
	return b.String()
}

func printHeader(stringBuilder *strings.Builder) {
	stringBuilder.WriteString("// Code generated by Why.css.\n")
	stringBuilder.WriteString("// DO NOT EDIT!\n\n")
	stringBuilder.WriteString("package main\n\n")
}

func printImports(stringBuilder *strings.Builder, stats []ast.Statement) {
	imports := getImports(stats)
	stringBuilder.WriteString("import (\n")
	for _, imp := range imports {
		stringBuilder.WriteString(fmt.Sprintf("    \"%s\"\n", imp))
	}
	stringBuilder.WriteString(")\n\n")
}

func getImports(stats []ast.Statement) []string {
	var imports []string
	for _, stat := range stats {
		if imp, ok := stat.(ast.Import); ok {
			imports = append(imports, imp.Name)
		}
	}
	return imports
}

func generateStatement(stat ast.Statement) string {
	switch s := stat.(type) {
	case ast.Assign:
		return fmt.Sprintf("%s := %s", s.Name, generateExpression(s.Expr))
	case ast.Print:
		return fmt.Sprintf("fmt.Println(%s)", generateExpression(s.Expr))
	case ast.Import:
		return ""
	default:
		return "// unknown statement"
	}
}

func generateExpression(expr ast.Expression) string {
	switch e := expr.(type) {
	case ast.IntLiteral:
		return fmt.Sprintf("%d", e.Value)
	case ast.VarRef:
		return e.Name
	case ast.BinOp:
		return fmt.Sprintf("(%s %s %s)", generateExpression(e.Left), e.Op, generateExpression(e.Right))
	default:
		return "/* unknown expr */"
	}
}
